{
 "title": "Nolus-Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": {
     "query": "label_values(tendermint_consensus_height, chain_id)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(tendermint_consensus_height{chain_id=\"$chain_id\"}, instance)"
    }
   },
   {
    "name": "moniker",
    "label": "moniker",
    "query": {
     "query": "label_values(cosmos_validator_status, moniker)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Chain Helath", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "DS" },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "options": {
    "content": "<table style=\"width:100%; height:100%;border:0px solid black;\">\n     <tr>\n     <td style=\"text-align: center;vertical-align: middle;border:0px solid black; \"><center><img width=\"180px\" src=\"https://iili.io/HWivpNs.png\" /></td>\n     <td style=\"border:0px;\"><h1 style=\"font-family: 'Prompt', sans-serif;font-size: 36px;letter-spacing: 0px;word-spacing: 0px;color: #f08000;font-weight: normal;text-decoration: none;font-style: normal;font-variant: normal;text-transform: none;\">Nolus Protocol</h1> \n     </br> <h2 style=\"font-family: 'Prompt', sans-serif;font-size: 20px;color: #f08000;font-weight: normal;text-decoration: underline;font-style: italic;\">Dashboard by und3r</h2></td> \n     </tr>\n</table>"
   }
  },
  {
   "title": "Chain-ID",
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 1 },
   "options": {
    "content": "<p style=\"text-align:center;color: #f08000\"><span style=\"font-size:26px\">Nolus-rila</span></p>\n"
   },
   "targets": [
    { "expr": "$chain_id", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_height{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Validators",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators-tendermint_consensus_missing_validators{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Total TXs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_total_txs{chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Bonded Tokens",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power{chain_id=\"$chain_id\"}",
     "legendFormat": "{{NLS}}"
    }
   ]
  },
  {
   "title": "Block per Minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(tendermint_consensus_height{chain_id=\"$chain_id\"}[1m])"
    }
   ]
  },
  {
   "title": "Blocks per Minute",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(tendermint_consensus_height{chain_id=\"$chain_id\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Most Missed Blocks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cosmos_validators_missed_blocks{chain_id=\"$chain_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missed Blocks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validators_missed_blocks{chain_id=\"$chain_id\"} > 0) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed TXs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_mempool_failed_txs{chain_id=\"$chain_id\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unconfirmed TXs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_mempool_size{chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "tendermint_consensus_block_size_bytes{chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}